FusionSzef/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Script.Serialization;
using FusionPOS.Domain;
using NHibernate.Linq;

namespace FusionSzef
{
	public class ClientsSearchModel
	{
		public string Query { get; set; }
		public string NIP { get; set; }
	}
	
	[Authorize]
	public class ClientsController: BaseController
	{
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Index()
		{
			return RedirectToAction("List");	
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult List(ClientsSearchModel search)
		{
			SearchListModel<Client, ClientsSearchModel> model = new SearchListModel<Client, ClientsSearchModel>() { 
				SortString = Request.Params.GetOrDefault("sort", "+Name"),
				PageNumber = int.Parse(Request.Params.GetOrDefault("page", "0")),
				PageSize = 10,
				Template = search ?? new ClientsSearchModel()
			};
			
			if (!string.IsNullOrEmpty(search.NIP))
				model.Parameters.Add(m => m.NIP == search.NIP);
			
			if (!string.IsNullOrEmpty(search.Query))
				model.Parameters.Add(m => 
				    m.Name.Contains(search.Query) || 
				    m.Address.Contains(search.Query) || 
				    m.Description.Contains(search.Query) || 
				    m.PhoneNumber.Contains(search.Query));
			
			model.Fetch(DbSession);
			
			if (model.Items.Count() == 1)
				return RedirectToAction("Edit", new { Id = model.Items.First().Id });
			
			return View(model);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public JsonResult AjaxList()
		{
			var model = new DataTableModel<Client>(DbSession, Request.Params);
			return Json(model.Fetch(), JsonRequestBehavior.AllowGet);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Summary(long id)
		{
			Client client = DbSession.Get<Client>(id);
			if(client == null)
				return HttpNotFound("Klient nie istnieje");
			
			IEnumerable<OrderDish> dishes = DbSession.Query<OrderDish>().Where(i => i.Order.Client == client);
			IEnumerable<Order> orders = DbSession.Query<Order>().Where(p => p.Client == client);
			
			//ViewBag.Last = dishes.Max(p => p.Order.Time.Ticks).Dish.Name;

			OrderDish last = dishes.OrderBy(i => i.Order.Time).FirstOrDefault();
			OrderDish first = dishes.OrderByDescending(i => i.Order.Time).FirstOrDefault();
			
			IEnumerable<IEnumerable<OrderDish>> groups = dishes.GroupBy(i => i.Dish.Name);
			
			IEnumerable<OrderDish> max = groups.OrderBy(i => i.Count()).FirstOrDefault();
			string name = max.First().Dish.Name;
			//double overalTurnover =  DbSession.Query<Transaction>().Where(i => i.Client.Id == client.Id).Sum(i => i.TotalValue);
			ViewBag.Last = last.Dish.Name;
			ViewBag.FreqDish = name;
			IEnumerable< IEnumerable<OrderDish> > days =  dishes.GroupBy(i => i.Order.Time.DayOfWeek);
			ViewBag.WeekVisit = days.Where(p => days.All(r => p.Count() >= r.Count() )).First().First().Order.Time.DayOfWeek;

			decimal dayscount = (decimal)(DateTime.Now - first.Order.Time).TotalDays;
			decimal monthscount = dayscount / 31;
			decimal weeklyscount = dayscount / 368;
			
			//XXX orders.Sum poprawić na transaction
			ViewBag.DayliTurnover = dayscount != 0 ? orders.Sum(p => p.TotalValue) / dayscount
					: orders.Sum(p => p.TotalValue);
			ViewBag.MonthlyTurnover = dayscount != 0 ? orders.Sum(p => p.TotalValue) / monthscount
					: orders.Sum(p => p.TotalValue);
			ViewBag.WeeklyTurnover = dayscount != 0 ? orders.Sum(p => p.TotalValue) / weeklyscount
					: orders.Sum(p => p.TotalValue);
			ViewBag.OveralTurnover = orders.Sum (p => p.TotalValue);
			return View(client);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult SummaryTurnoverChart(long id, string type)
		{
			JavaScriptSerializer js = new JavaScriptSerializer();
			ViewBag.StartDate = DateTime.Today;
			ViewBag.Turnover =  js.Serialize(new int[] { 1, 2, 3, 10, 1, 4, 20, 1, 5 });
			return View();
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Edit(long? id)
		{
			Client c = id.HasValue ? DbSession.Get<Client>(id) : new Client();
			
			if (c == null)
				return HttpNotFound("Client not found");
			
			return View(c);
		}
		
		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult Save(Client client)
		{
			if (!ModelState.IsValid)
				return View("Edit", client);
			
			/* XXX */
			DbSession.Merge(client);
			return Redirect(Url.Action("List"));
		}
	}
}

FusionSzef/Controllers/ReservationsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using NHibernate;
using NHibernate.Linq;
using FusionPOS.Domain;

namespace FusionSzef
{
	public class ReservationsController: BaseController
	{
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Index()
		{
			return RedirectToAction("List");
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult List()
		{
			return View();
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Edit(long? id)
		{
			return base.AbstractEdit<Reservation>(id);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Calendar(int? year, int? month, int? day, int? monthly)
		{			
			DateTime frm;
			DateTime to;
			
			if(year.HasValue)
			{
				if(monthly.HasValue)
				{
					if(monthly.Value == 1)
					{
						frm = new DateTime(year.Value, month.Value, 1);
						to = frm.AddDays(DateTime.DaysInMonth(year.Value, month.Value)); 	
					}
					else
					{
						frm = new DateTime(year.Value, month.Value, day.Value);
						to = frm.AddDays(7);	
					}
				}
				else
				{
					frm = new DateTime(year.Value, month.Value, day.Value);
					to = frm.AddDays(7);
				}
			}
			else
			{
				frm = DateTime.Now.AddDays(-1 * (int)DateTime.Now.DayOfWeek + 1);
				to = DateTime.Now.AddDays(7-(int)DateTime.Now.DayOfWeek);	
			}
			
			frm = frm + (new TimeSpan(0,0,0));
			
			to = to + (new TimeSpan(0,0,0));
			ViewBag.Entities = DbSession.Query<Reservation>()
				.Where(p => p.Date>=frm)
				.Where(p => p.Date<=to).ToList();
			//XXX
			//Z pliku xml godziny otwarcia i zamknięcia
			if(!monthly.HasValue || (monthly.HasValue ? monthly.Value == 0 : true))
			{
				ViewBag.StartHour = new DateTime(2000, 1, 1, 7, 0,0);
				ViewBag.EndHour = new DateTime(2000, 1, 1, 22, 0,0);			
			}
			
			ViewBag.From = frm;
			ViewBag.To = to;
			
			ViewBag.Monthly = monthly.HasValue ? monthly.Value : 0;
			return View();
		}
	}
}

FusionSzef/Views/Reservations/Calendar.cshtml
@model FusionPOS.Domain.Reservation
@using FusionPOS.Domain
@using FusionSzef

@section commands {
	<li><a href="@Url.Action("List")">Lista rezerwacji</a></li>
}

@if ( ViewBag.Monthly == 0 )
{
  <div>
   <table width="100%">
    <tr>
     <td width="10%">
      <a href="@Url.Action("Calendar", "Reservations",
       new {year = ViewBag.From.AddDays(-7).Year, month = ViewBag.From.AddDays(-7).Month, day = ViewBag.From.AddDays(-7).Day})">Wcześniej</a>
     </td>
     <td>Od: @ViewBag.From.ToString("dd-MM-yyy") do: @ViewBag.To.ToString("dd-MM-yyy")</td>
     <td width="10%">
      <a href="@Url.Action("Calendar", "Reservations",
       new {year = ViewBag.From.AddDays(7).Year, month = ViewBag.From.AddDays(7).Month, day = ViewBag.From.AddDays(7).Day})">Później</a>
     </td>
    </tr>
   </table>
   <table width="100%">
    <tr>
     <th width="10%">Godzina</th>
	@for(int i=0; i<7; ++i)
	{
		@:<th width="13%"><p>
		@((DayOfWeek)(i+1<7 ? i+1 : 0))
		@:</p><p>
		@ViewBag.From.AddDays(i).ToString("dd-MM")
		@:</p></th>
	}
    </tr>

	@{
		
		IEnumerable<Reservation> res = ViewBag.Entities;
		DateTime now = new DateTime(ViewBag.From.Year, ViewBag.From.Month, ViewBag.From.Day,
					ViewBag.StartHour.Hour, ViewBag.StartHour.Minute, ViewBag.StartHour.Second);
	}
	@for(double i=ViewBag.StartHour.Hour; i<ViewBag.EndHour.Hour; i+=1)
	{
		DateTime dayA = new DateTime(now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second);
		DateTime dayB = new DateTime(now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second);
		@:<tr>
		dayB = dayB.AddMinutes(60);
		@:<td>@dayA.ToString("hh:mm") - @dayB.ToString("hh:mm")</td>
		for(int j=0; j<7; ++j)
		{
			@:<td>
			foreach(Reservation r in res.Where(p => p.Date>=dayA && p.Date<=dayB))
			{
			<text>
				<ol>
				String.Format("<li><a href="#">{0}</a></li>", r.ParentClient.Name)
				</ol>
			</text>
			}
			@:</td>
			dayA.AddDays(1);
			dayB.AddDays(1);
		}

		@:</tr>
		now = now.AddMinutes(60);
	}
	
     <tr>
      <td colspan="8"><a href="@Url.Action("Calendar", "Reservations",
       new {year=ViewBag.From.Year, month=ViewBag.From.Month, day=1, monthly=1})">Widok miesięczny</a></td>
    </tr>
   </table>
  </div>
} else {
  @:<div>
   <table width="100%">
    <tr>
     <td width="10%">
      <a href="@Url.Action("Calendar", "Reservations",
       new {year = ViewBag.From.AddMonths(-1).Year, month = ViewBag.From.AddMonths(-1).Month, 
       day = ViewBag.From.AddMonths(-1).Day, monthly=1})">Wcześniej</a>
     </td>
     <td>Od: @ViewBag.From.ToString("MM-yyyy") do: @ViewBag.To.ToString("MM-yyyy")</td>
     <td width="10%">
      <a href="@Url.Action("Calendar", "Reservations",
       new {year = ViewBag.From.AddMonths(1).Year, month = ViewBag.From.AddMonths(1).Month, 
       day = ViewBag.From.AddMonths(1).Day, monthly=1})">Później</a>
     </td>
    </tr>
   </table>
   @:<table width=100%>
    @:<tr>
     	for(int i=0; i<7; ++i)
	{
		@:<th width="13%"><p>
		@((DayOfWeek)(i+1<7 ? i+1 : 0))
		@:</p></th>
	}	
   @:</tr>
   	

	DateTime now = new DateTime(ViewBag.From.Year, ViewBag.From.Month, 1, 0, 0, 0);
		
	@:<tr>
	if((int)now.DayOfWeek != 1)
	{
		@:<td colspan="@((int)now.DayOfWeek-1>=0 ? (int)now.DayOfWeek-1 : 6)"> </td>
	}

	
	for(int i=1; i<=DateTime.DaysInMonth(ViewBag.From.Year, ViewBag.From.Month); ++i)
	{
		if( ((int)now.DayOfWeek == 1) && (i!=1) )
		{
			@:</tr>
			@:<tr>
		}
		@:<td><p>@now.ToString("dd")</p>
		
		IEnumerable<Reservation> res = ViewBag.Entities;
		foreach(Reservation r in res.Where(p => (p.Date.Day == now.Day) && (p.Date.Month == now.Month) ))
		{
			<text>
				<p> * <a href="#">@r.Date.ToString("mm:hh") @r.ParentClient.Name</a></p>
			</text>
		}
		@:</td>
		now = now.AddDays(1);
	}
    @:</tr>
    <text>
    <tr>
     <td colspan="8"><a href="@Url.Action("Calendar", "Reservations",
       new {year=ViewBag.From.Year, month=ViewBag.From.Month, day=1, monthly=0})">Widok tygodniowy</a></td>
     </tr>
    </text>
   @:</table>
  @:</div>
}

FusionSzef/Views/Reservations/Edit.cshtml
@model FusionPOS.Domain.Reservation
@using FusionSzef
@section commands {
	<li><a href="@Url.Action("List")">Anuluj</a></li>
	<li><a class="submit">Zapisz</a></li>
}

@{ Html.Form()
	.Add(new HiddenDataField(), m => m.Id)
	.Add(new TextField("Data", "datepicker"), m => m.Date)
	.Add(new AutocompleteField("Klient", Url.RouteUrl("AjaxListAutocomplete", new { domain = "Client" })), m => m.ParentClient)
	.Add(new AutocompleteField("Stolik", Url.RouteUrl("AjaxListAutocomplete", new { domain = "Table" })), m => m.ParentTable)
	.Add(new SubmitButton("Zapisz"));
}

FusionSzef/Views/Reservations/List.cshtml
@using FusionSzef
@using FusionPOS.Translations
@section subsections {
	<li><a href="@Url.Action("Index", "Clients")">Klienci</a></li>
	<li><a href="@Url.Action("Index", "Reservations")">Rezerwacje</a></li>
}

@section commands {
	<li><a href="@Url.Action("Edit")">Dodaj rezerwację</a></li>
	<li><a href="@Url.Action("Calendar")">Kalendarz rezerwacji</a></li>
}

<table
    feature="datatable"
    source="@Url.RouteUrl("AjaxList", new { domain = "Reservation" })"
    row-edit="@Url.Action("Edit")">
	<td name="Data" property="Date" type="date"/>
	<td name="Klient" property="ParentClient.Name"/>
	<td name="Stolik" property="ParentTable.Name"/>
	<td name="Usuń" property="Id" class="noclick">{{#__deleteLink}}@Url.Action("Delete"){{/__deleteLink}}</td>
</table>