FusionSzef/Controllers/DishesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Script.Serialization;
using NHibernate;
using NHibernate.Linq;
using FusionPOS;
using FusionPOS.Domain;

namespace FusionSzef
{
	public class IngredientModel
	{
		public string Type { get; set; }
		public long Id { get; set; }
		public string Name { get; set; }
		public int Amount { get; set; }
		public bool Optional { get; set; }
	}
	
	[Authorize]
	public class DishesController: BaseController
	{
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Index()
		{
			return RedirectToAction("List");	
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult ListGroups()
		{
			return View();
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult EditGroup(long? id)
		{
			DishGroup u = id.HasValue ? DbSession.Get<DishGroup>(id) 
			    : new DishGroup();
			JavaScriptSerializer js = new JavaScriptSerializer();
			IList<Dish> Dishes = id.HasValue ? DbSession.Query<Dish>()
			    .Where(p => p.Groups.Contains(u)).ToList() :
			    new List<Dish>();
			
			ViewBag.Dishes = Dishes != null ? js.Serialize(Dishes.Select(i => new {
				Id = i.Id,
				Name = i.Name
			})) : "{}";
			return View (u);
		}
		
		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult EditGroup(DishGroup gr)
		{
			using(ITransaction tr = DbSession.BeginTransaction())
			{
				gr.Dishes.Each(p => DbSession.Refresh(p));
				DbSession.Merge(gr);
				tr.Commit();
			}
			return RedirectToAction("ListGroups");
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult DeleteGroup(long id, int? confirm)
		{
			DishGroup u = DbSession.Get<DishGroup>(id);
			
			if (u == null)
				return HttpNotFound("Dish group not found");
		
			if (confirm.HasValue && confirm != 0) {
				using (ITransaction tx = DbSession.BeginTransaction()) {
					DbSession.Delete(u);
					tx.Commit();
				}
				return RedirectToAction("ListGroups");
			}
			return View(u);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Edit(long? id, long? parent)
		{
			JavaScriptSerializer js = new JavaScriptSerializer();
			Dish u = id.HasValue ? DbSession.Get<Dish>(id) : new Dish() { Recipe = new Recipe() };
			
			if (u == null)
				return HttpNotFound("Dish not found");
			
			if (parent.HasValue) {
				DishCategory c = DbSession.Get<DishCategory>(parent);
				if (c == null)
					return HttpNotFound("Parent category not found");
				
				u.Categories = new List<DishCategory>();
				u.Categories.Add(c);
			}
			
			ViewBag.TaxRates = DbSession.Query<Tax>().ToDictionary(i => (int)i.Id, i => i.Name);
			ViewBag.Kitchens = DbSession.Query<Kitchen>().ToDictionary(i => (int)i.Id, i => i.Name);
			
			if (u.Recipe.Ingredients != null) {
				IList<object> ingredients = new List<object>();
				foreach(RecipeIngredient ingredient in u.Recipe.Ingredients)
				{
					if(ingredient is RecipeIngredientIngredient)
					{
						RecipeIngredientIngredient i = ingredient as RecipeIngredientIngredient;
						ingredients.Add(new {
							Id = i.Ingredient.Id,
							Type = "Ingredient",
							Unit = Enum.GetName(typeof(UnitOfMeasure), i.Ingredient.Unit),
							Name = i.Name,
							Amount = i.Amount,
							Optional = i.Optional
						});
					}
					
					if(ingredient is RecipeIngredientDish)
					{
						RecipeIngredientDish i = ingredient as RecipeIngredientDish;
						ingredients.Add(new {
							Id = ingredient.Component.Id,
							Type = "Dish",
							Unit = "szt.",
							Name = i.Name,
							Amount = i.Amount,
							Optional = i.Optional
						});
					}
					
					if(ingredient is RecipeIngredientIngredientGroup)
					{
						
					}
					
					if(ingredient is RecipeIngredientDishGroup)
					{
						
					}
				}
				
				ViewBag.Ingredients = js.Serialize(ingredients);
			} else
				ViewBag.Ingredients = "{}";
			
			ViewBag.Categories = u.Categories != null ? js.Serialize(u.Categories.Select(i => new {
				Id = i.Id,
				Name = i.Name
			})) : "{}";
			
			ViewBag.Groups = u.Groups != null ? js.Serialize(u.Groups.Select(i => new { 
				Id = i.Id,
				Name = i.Name })) : "{}";
	
			return View(u);
		}
		
		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult Edit(Dish model, List<IngredientModel> ingredients)
		{
 			if(model.Categories != null)
			{
				
				model.Categories.RemoveDuplicates(i => i.Id);
				model.Categories.ForEach(i => DbSession.Load(i, i.Id));
			}
			if(model.Groups != null)
			{
				model.Groups.RemoveDuplicates(i => i.Id);
				model.Groups.ForEach(i => DbSession.Load(i, i.Id));
			}
			model.Recipe.Ingredients = new List<RecipeIngredient>();
			if(model.Id != 0)
				model.Recipe.Id = model.Id;
			else
				model.Recipe.Dish = model;

			
			using (ITransaction tx = DbSession.BeginTransaction()) {
				
				if(model.Id != 0) 
					model = DbSession.Merge(model);
				ingredients.RemoveDuplicates(i => i.Id);
				foreach (IngredientModel i in ingredients) {
					if(i.Type == "Ingredient")
					{       
						RecipeIngredientIngredient ingredient = new RecipeIngredientIngredient();
						ingredient.Amount = i.Amount;
						ingredient.Optional = i.Optional;
						ingredient.Recipe = model.Recipe;
						ingredient.Ingredient = DbSession.Get<Ingredient>(i.Id);
						model.Recipe.Ingredients.Add(ingredient);
					}
					
					if(i.Type == "Dish")
					{
						RecipeIngredientDish ingredient = new RecipeIngredientDish();
						ingredient.Amount = i.Amount;
						ingredient.Optional = i.Optional;
						ingredient.Recipe = model.Recipe;
						ingredient.Dish = DbSession.Get<Dish>(i.Id);
						model.Recipe.Ingredients.Add(ingredient);	
					}
					
					if(i.Type == "IngredientGroup")
					{
						RecipeIngredientIngredientGroup ingredient = new RecipeIngredientIngredientGroup();
						ingredient.Amount = 1;
						ingredient.Optional = i.Optional;
						ingredient.Recipe = model.Recipe;
						ingredient.IngredientGroup = DbSession.Get<IngredientGroup>(i.Id);
						model.Recipe.Ingredients.Add(ingredient);
					}
					
					if(i.Type == "DishGroup")
					{
						RecipeIngredientDishGroup ingredient = new RecipeIngredientDishGroup();
						ingredient.Amount = 1;
						ingredient.Optional = i.Optional;
						ingredient.Recipe = model.Recipe;
						ingredient.DishGroup = DbSession.Get<DishGroup>(i.Id);
						model.Recipe.Ingredients.Add(ingredient);
					}
				}
				
				
				if(model.Id == 0)
				{
					DbSession.Save(model);
					DbSession.Save(model.Recipe);
				}
				tx.Commit();
			}
			
			return RedirectToAction("List", "Categories");
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public JsonResult AjaxList(long id)
		{
			if(id != 0)
			{
				DishCategory category = DbSession.Get<DishCategory>(id);
				return Json(new { aaData = category.Dishes.Where(i => !i.Deleted) }, JsonRequestBehavior.AllowGet);
			}
			
			return Json (new { aaData = DbSession.Query<Dish>().Where(i => i.Categories.Count == 0 && !i.Deleted) }, JsonRequestBehavior.AllowGet);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public JsonResult AjaxListAutocomplete(string term)
		{
			IList list = DbSession.Query<Dish>()
			    .Where(i => i.Name.Contains(term))
			    .Select(i => new {label = i.Name, id = i.Id}).ToList();
			return Json(list, JsonRequestBehavior.AllowGet);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public JsonResult AjaxListGroupsAutocomplete(string term)
		{
			return Json(DbSession.Query<DishGroup>()
			    .Where(i => i.Name.Contains(term))
			    .Select(i => new {label = i.Name, id = i.Id}),
			    JsonRequestBehavior.AllowGet);
		}
		
		[AcceptVerbs(HttpVerbs.Get)]
		public ActionResult Delete(long id)
		{
			using (ITransaction tx = DbSession.BeginTransaction())
			{
				Dish dish = DbSession.Get<Dish>(id);
				dish.Deleted = true;
				DbSession.Update(dish);
				tx.Commit();
			}
			
			return RedirectToAction("List", "Categories");
		}
	}
}

FusionSzef/Views/Dishes/DeleteGroup.cshtml
@model FusionPOS.Domain.DishGroup
@using FusionSzef
@section commands {
	<li><a href="@Url.Action("List")">Anuluj</a></li>
}

Czy na pewno chcesz usunąć grupę @Model.Name?

<a href="@Url.Action("DeleteGroup", new { id = Model.Id, confirm = 1 })">Tak</a>
<a href="@Url.Action("ListGroups")">Nie</a>

FusionSzef/Views/Dishes/Edit.cshtml
@model FusionPOS.Domain.Dish
@using FusionSzef


@section commands {
	<li><a href="@Url.Action("List", "Categories")">Anuluj</a></li>
	<li><a class="submit">Zapisz</a></li>
}

@section script {
	$.instance = {
		ingredients: @Html.Raw(ViewBag.Ingredients),
		groups: @Html.Raw(ViewBag.Groups),
		categories: @Html.Raw(ViewBag.Categories)
	}

	$(function() {
		$("#add-category").click(function(event, data) {
			$("#categories").dataTable().fnAddData({Id: 0, Name: ""});
		});
		
		$("#add-group").click(function(event, data) {
			$("#groups").dataTable().fnAddData({Id: 0, Name: ""});
		});
		
		$("#add-ingredient").click(function(event, data) {
			$("#recipe").dataTable().fnAddData({Id: 0, Type: "", Name: "", Amount: 1, Optional: false, Unit: ""});
			$.pos.reload($("#recipe")); 
		});
		
		$(".ingredient-type-select").change(function() {
			var tr = $(this).parents("tr");
			var td = $(".ingredient-value", tr);
			var old = $("input", td);
			alert("huj");
			td.html("");
		
			$("<input>")
			    .attr("type", "text")
			    .attr("hidden-id", old.attr("hidden-id"))
			    .attr("remote", $("option:selected", this).attr("remote"))
			    .appendTo(td)
			    .combo()
			    .removeAttr("remote")
			    .bind("autocompleteselect", function(event, ui) {
				$(".ingredient-unit", tr).html(ui.item.unit);
			    });
		});
		
		$("#recipe").dataTable().fnAdjustColumnSizing();
	});
}

@using(var form = Html.Form("/Dishes/Edit")) {	
<div id="tabs" feature="tabs">	
	<ul>
		<li><a href="#basic-tab">Podstawowe informacje</a></li>
		<li><a href="#recipe-tab">Receptura</a></li>
		<li><a href="#descriptions-tab">Opisy</a></li>
	</ul>
	<div id="basic-tab" class="form">
		@{ form
			.Add(new HiddenDataField(), m => m.Id)
			.Add(new TextField("Nazwa"), m => m.Name)
			.Add(new SelectField("Stawka VAT", ViewBag.TaxRates), m => m.Tax.Id)
			.Add(new SelectField("Drukarka kuchenna", ViewBag.Kitchens), m => m.Kitchen.Id)			
			.Add(new FormHeader("Cena 1"))
			.Add(new TextField("Netto"), m => m.Price1)
			.Add(new TextField("Brutto"), m => m.Price2)
			.Add(new FormHeader("Cena 2"))
			.Add(new TextField("Netto"), m => m.Price2)
			.Add(new TextField("Brutto"), m => m.Price2)
			.Add(new FormHeader("Rabaty"))				
			.Add(new TextField("Rabat kwotowy"), m => m.RebateAmount)
			.Add(new TextField("Rabat procentowy"), m => m.RebatePercent)
			.Add(new TextField("Ilość puntków"), m => m.Points);	
		}
		<h2>Dodaj do kategorii:</h2>
		<table style="float: left; width: 40%;" feature="datatable" id="categories" type="form" data="$.instance.categories" large="false" sortable="false">
			<td name="Nazwa kategorii" property="Name">
				<input feature="autocomplete" hidden-id="Categories[{{iDataRow}}].Id" value-id="{{aData.Id}}" value-name="{{aData.Name}}"
		 		    remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "DishCategory"})"/>
			</td>
			<td class="hidden">{{#__indexer}}Categories{{/__indexer}}</td>
			<td name="Usuń">{{{__delete}}}</td>		
		</table>
		<button type="button" id="add-category">Dodaj</button>
		<h2>Dodaj do grup:</h2>
		<table style="float: left; width: 40%;" feature="datatable" id="groups" type="form" data="$.instance.groups" large="false" sortable="false">
			<td name="Nazwa kategorii" property="Name">
				<input feature="autocomplete" hidden-id="Groups[{{iDataRow}}].Id" value-id="{{aData.Id}}" value-name="{{aData.Name}}"
				    remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "DishGroup"})"/>
			</td>
			<td class="hidden">{{#__indexer}}Groups{{/__indexer}}</td>
			<td name="Usuń">{{{__delete}}}</td>	
		</table>
		<button type="button" id="add-group">Dodaj</button>
	</div>
	<div id="recipe-tab">
		<div id="recipe-tabs">
			<table feature="datatable" id="recipe" type="form" data="$.instance.ingredients" large="false" sortable="false">
				<td name="Typ" property="Type" width="15%">
					<select name="Ingredients[{{iDataRow}}].Type" class="ingredient-type-select" value="{{aData.Type}}">
						<option value="Ingredient" remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "Ingredient"})">składnik</option>
						<option value="Dish" remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "Dish"})">potrawa</option>
						<option value="IngredientGroup" remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "IngredientGroup"})">grupa składników</option>
						<option value="DishGroup" remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "DishGroup"})">grupa potraw</option>
					</select>
				</td>
				<td name="Wartość" property="Id" class="ingredient-value" width="40%">
					<input feature="autocomplete" hidden-id="Ingredients[{{iDataRow}}].Id"
					    remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "Ingredient" })"
					    value-id="{{aData.Id}}" value-name="{{aData.Name}}"/>
				</td>
				<td name="Ilość" property="Amount" width="30%">
					<input class="ingredient-amount" type="text" name="Ingredients[{{iDataRow}}].Amount" value="{{aData.Amount}}"/>
					<span class="ingredient-unit">{{aData.Unit}}</span>
				</td>
				<td name="Dodatek" property="Optional">
					<input name="Ingredient[{{iDataRow}}].Optional" type="checkbox" {{#aData.Optional}}checked="checked"{{/aData.Optional}}/>
				</td>
				<td>{{{__delete}}}</td>
			</table>
			<button type="button" id="add-ingredient">Dodaj</button>
		</div>
	</div>
	<div id="descriptions-tab" class="form">
		@{ form
			.Add(new TextAreaField("Opis produktu"), m => m.Description)
			.Add(new TextAreaField("Sposób przygotowania"), m => m.Recipe.Protips);
		}
	</div>
</div> 
@form.Add(new SubmitButton("Zapisz"))
}

FusionSzef/Views/Dishes/EditGroup.cshtml
@model FusionPOS.Domain.DishGroup
@using FusionSzef

@section commands {
	<li><a href="@Url.Action("ListGroups", "Dishes")">Anuluj</a></li>
	<li><a class="submit">Zapisz</a></li>
}

@section script {
	$.instance = {
		dishes: @Html.Raw(ViewBag.Dishes),
	}
	
	$(function() {
		$("#add-dish").click(function(event, data) {
			$("#dishes").dataTable().fnAddData({Id: 0, Name: ""});
		});
	});
}

@using(var form = Html.Form("/Dishes/EditGroup")) {
	form
		    .Add(new HiddenDataField(), u => u.Id)
		    .Add(new TextField("Nazwa"), u => u.Name);
	
	<h2>Zawartość grupy:</h2>
	
	<table style="float: left; width: 40%;" feature="datatable" id="dishes" type="form" data="$.instance.dishes" large="false" sortable="false">
		<td name="Nazwa dania" property="Name">
			<input feature="autocomplete" hidden-id="Dishes[{{iDataRow}}].Id" value-id="{{aData.Id}}" value-name="{{aData.Name}}"
	 		    remote="@Url.RouteUrl("AjaxListAutocomplete", new { domain = "Dish" })"/>
		</td>
		<td class="hidden">{{#__indexer}}Dishes{{/__indexer}}</td>
		<td name="Usuń">{{{__delete}}}</td>		
	</table>
	<button type="button" id="add-dish">Dodaj</button>
	@form.Add(new SubmitButton("Zapisz"));
}

FusionSzef/Views/Dishes/ListGroups.cshtml
@using FusionSzef

@section subsections {
	<li><a href="@Url.Action("List", "Categories")">Produkty i kategorie</a></li>
	<li>@Html.ActionLink("Grupy produktów", "ListGroups", "Dishes")</li>
}

@section commands {
	<li><a href="@Url.Action("EditGroup")">Dodaj grupę produktów</a></li>
}

<table feature="datatable" id="table" 
    source="@Url.RouteUrl("AjaxList", new { domain = "DishGroup" })" 
    row-edit="@Url.Action("EditGroup")">
	<td name="Nazwa" property="Name"/>
	<td name="Usun" property="Id" class="noclick">{{#__deleteLink}}@Url.Action("DeleteGroup"){{/__deleteLink}}</td>
</table>